/** Generated by itemis CREATE code generator. */
package umons;

import com.yakindu.core.*;

public class Main {

   public static void main(String[] args) {
        CDPlayer sm = new CDPlayer();
        sm.setTimerService(new TimerService());
        MyOperationCallback callback = new MyOperationCallback();
        sm.cD().setOperationCallback(callback);

        // enter the state machine and start the timer
        sm.enter();
        System.out.println(callback + ". playing is " +  sm.rC().getIsPlaying());

        // turn on the remote control
        sm.rC().raiseOnOff();
        sm.runCycle();
        sm.runCycle();
        System.out.println(callback);

        // ask the remote control to start playing
        sm.rC().raisePlayPause();
        sm.runCycle();
        sm.runCycle();
        System.out.println(callback + ". playing is " + sm.rC().getIsPlaying());

        // ask the remote control to pause playing
        sm.rC().raisePlayPause();
        sm.runCycle();
        sm.runCycle();
        System.out.print(callback + ". playing is " + sm.rC().getIsPlaying());

        sm.rC().raiseStop();
        sm.runCycle();
        sm.runCycle();
        System.out.println(callback);

        sm.rC().raiseOnOff();
        sm.runCycle();
        sm.runCycle();
        System.out.println(callback);

        sm.exit();
        System.out.println("Done.");
   }
}