/** Generated by itemis CREATE code generator. */

package test;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(Suite.class)
@SuiteClasses({
	RemoteControlTest.class,
	WhiteboxCDPlayerTest.class,
	BlackboxCDPlayerTest.class
	})
public class CDPlayerTestSuite {
}
